import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import Providers from "@/store/Providers";
import _layout from "./_layout";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" className="dark">
            <body>
                <_layout>
                    <Providers>
                        {children}
                    </Providers>
                    <Toaster />
                </_layout>
            </body>
        </html>
    );
}
